#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _A_reg(void);
extern void _AMPA_reg(void);
extern void _ElectSyn_reg(void);
extern void _GABAa_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _NMDA_reg(void);
extern void _Nca_reg(void);
extern void _OFThpo_reg(void);
extern void _OFThresh_reg(void);
extern void _ar_reg(void);
extern void _cad_reg(void);
extern void _cadad_reg(void);
extern void _cal_reg(void);
extern void _cat_reg(void);
extern void _expsynstdp_reg(void);
extern void _iholmw_reg(void);
extern void _izhi2003a_reg(void);
extern void _izhi2003b_reg(void);
extern void _izhi2007a_reg(void);
extern void _izhi2007b_reg(void);
extern void _k2_reg(void);
extern void _ka_reg(void);
extern void _kacurrent_reg(void);
extern void _kahp_reg(void);
extern void _kc_reg(void);
extern void _kca_reg(void);
extern void _kdr_reg(void);
extern void _kdrcurrent_reg(void);
extern void _km_reg(void);
extern void _km2_reg(void);
extern void _kv_reg(void);
extern void _nacurrent_reg(void);
extern void _naf_reg(void);
extern void _nap_reg(void);
extern void _naz_reg(void);
extern void _vecevent_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," netpyne-course-2021/A.mod");
    fprintf(stderr," netpyne-course-2021/AMPA.mod");
    fprintf(stderr," netpyne-course-2021/ElectSyn.mod");
    fprintf(stderr," netpyne-course-2021/GABAa.mod");
    fprintf(stderr," netpyne-course-2021/MyExp2SynBB.mod");
    fprintf(stderr," netpyne-course-2021/MyExp2SynNMDABB.mod");
    fprintf(stderr," netpyne-course-2021/NMDA.mod");
    fprintf(stderr," netpyne-course-2021/Nca.mod");
    fprintf(stderr," netpyne-course-2021/OFThpo.mod");
    fprintf(stderr," netpyne-course-2021/OFThresh.mod");
    fprintf(stderr," netpyne-course-2021/ar.mod");
    fprintf(stderr," netpyne-course-2021/cad.mod");
    fprintf(stderr," netpyne-course-2021/cadad.mod");
    fprintf(stderr," netpyne-course-2021/cal.mod");
    fprintf(stderr," netpyne-course-2021/cat.mod");
    fprintf(stderr," netpyne-course-2021/expsynstdp.mod");
    fprintf(stderr," netpyne-course-2021/iholmw.mod");
    fprintf(stderr," netpyne-course-2021/izhi2003a.mod");
    fprintf(stderr," netpyne-course-2021/izhi2003b.mod");
    fprintf(stderr," netpyne-course-2021/izhi2007a.mod");
    fprintf(stderr," netpyne-course-2021/izhi2007b.mod");
    fprintf(stderr," netpyne-course-2021/k2.mod");
    fprintf(stderr," netpyne-course-2021/ka.mod");
    fprintf(stderr," netpyne-course-2021/kacurrent.mod");
    fprintf(stderr," netpyne-course-2021/kahp.mod");
    fprintf(stderr," netpyne-course-2021/kc.mod");
    fprintf(stderr," netpyne-course-2021/kca.mod");
    fprintf(stderr," netpyne-course-2021/kdr.mod");
    fprintf(stderr," netpyne-course-2021/kdrcurrent.mod");
    fprintf(stderr," netpyne-course-2021/km.mod");
    fprintf(stderr," netpyne-course-2021/km2.mod");
    fprintf(stderr," netpyne-course-2021/kv.mod");
    fprintf(stderr," netpyne-course-2021/nacurrent.mod");
    fprintf(stderr," netpyne-course-2021/naf.mod");
    fprintf(stderr," netpyne-course-2021/nap.mod");
    fprintf(stderr," netpyne-course-2021/naz.mod");
    fprintf(stderr," netpyne-course-2021/vecevent.mod");
    fprintf(stderr, "\n");
  }
  _A_reg();
  _AMPA_reg();
  _ElectSyn_reg();
  _GABAa_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _NMDA_reg();
  _Nca_reg();
  _OFThpo_reg();
  _OFThresh_reg();
  _ar_reg();
  _cad_reg();
  _cadad_reg();
  _cal_reg();
  _cat_reg();
  _expsynstdp_reg();
  _iholmw_reg();
  _izhi2003a_reg();
  _izhi2003b_reg();
  _izhi2007a_reg();
  _izhi2007b_reg();
  _k2_reg();
  _ka_reg();
  _kacurrent_reg();
  _kahp_reg();
  _kc_reg();
  _kca_reg();
  _kdr_reg();
  _kdrcurrent_reg();
  _km_reg();
  _km2_reg();
  _kv_reg();
  _nacurrent_reg();
  _naf_reg();
  _nap_reg();
  _naz_reg();
  _vecevent_reg();
}
